### ISSUE TITLE
ImportError: No module named fpdf (but fpdf is installed)

### ISSUE THREAD

**Issue by Wikinaut** [ola-ct/flippy#4]
`pip list` gives
...
fpdf (1.7.2)
...

and 
`python flippy.py` gives

  File "flippy.py", line 13, in <module>
    from fpdf import FPDF
ImportError: No module named fpdf

**Comment by 607011** [comment]
Operating system? Python version?

fpdf installed with `pip` of the same Python version?

**Comment by Wikinaut** [comment]
- OpenSuse Tumbleweed

**Comment by Wikinaut** [comment]
python --version
Python 2.7.10

The packages are
/usr/lib/python3.4/site-packages/fpdf/

Strange. How to repair ?

**Comment by Wikinaut** [comment]
If I however use

`python3 flippy.py` then your script throws:

  File "flippy.py", line 111
    print 'Opening {} ...'.format(self.input_file_name)
                         ^
SyntaxError: invalid syntax

**Comment by 607011** [comment]
Which version of flippy.py are you trying to use? The one described in the corresponding c't article? Get it [here](https://github.com/ola-ct/flippy/releases/tag/ct1216)!

**Comment by Wikinaut** [comment]
from github abc672ee92db42eba744db7b64f16d90d27149f2

**Comment by 607011** [comment]
@Wikinaut HEAD is an outdated version that does not correspond to the [c't article](http://heise.de/-3198021). Again, [get the correct version here](https://github.com/ola-ct/flippy/releases/tag/ct1216).

**Comment by Wikinaut** [comment]
```
git checkout tags/ct1216
python3 flippy.py --input samples/lemoncat.mp4 --output flipbook-lemoncat.pdf
```

works for me.
