### ISSUE TITLE
errore form fpdf import FPDF

### ISSUE THREAD

**Issue by vmavo** [ola-ct/flippy#9]
Buon Giorno, python 3.7, fpdf versione 1.7.2
dal comando from il modulo FPDF non risulta caricabile:

import os
from fpdf import FPDF
import PyPDF2

def img2pdf(folder_path, name):
    pdf = FPDF('L', 'pt', 'letter')
    pdf.add_page()
    pdf.image(folder_path + '/' + name + '.png')
    pdf.output(folder_path + '/' + name + '1.pdf', 'F')

    inputFile = open(folder_path + '/' + name + '1.pdf', 'rb')
    pdfReader = PyPDF2.PdfFileReader(inputFile)

    output_pdf = PyPDF2.PdfFileWriter()
    output_pdf.addPage(pdfReader.getPage(1))

    output_pdf.encrypt(str.lower(name))
    with open(folder_path + '/' + name + '.pdf', "wb") as out_file:
        output_pdf.write(out_file)

    out_file.close()
    inputFile.close()

    os.remove(folder_path + '/' + name + '.png')
    os.remove(folder_path + '/' + name + '1.pdf')

dir= r"C:\Users\v.mavilla\Desktop"
file= r"Preventivo-121_2020.pdf"
img2pdf(dir,file)

ottengo l errore:
C:\Users\\AppData\Local\Programs\Python\Python37-32\python.exe "C:/MyPyton/Progetti/Libretti Jungherich/fpdf.py"
Traceback (most recent call last):
  File "C:/MyPyton/Progetti/Libretti Jungherich/fpdf.py", line 2, in <module>
    from fpdf import FPDF
  File "C:\MyPyton\Progetti\Libretti Jungherich\fpdf.py", line 2, in <module>
    from fpdf import FPDF
ImportError: cannot import name 'FPDF' from 'fpdf' (C:\MyPyton\Progetti\Libretti Jungherich\fpdf.py)

**Comment by 607011** [comment]
It would be helpful to submit issues in English, not in Italian.

However, I've upgrade the code to Python 3. Maybe that helps …

**Comment by 607011** [comment]
Your issue doesn't refer to flippy. Please seek advice elsewhere. Sorry.
